### ISSUE TITLE
invalid token

### ISSUE THREAD

**Issue by steveoh** [agrc/PEL#43]
handle invalid token on gp submissions.

**Comment by stdavis** [comment]
What do you mean by this? If there is a bad token sent to the PEL gp tasks? Or is this related to https://redmine.dts.utah.gov/issues/28338?

**Comment by steveoh** [comment]
Yeah related.

Steve Gourley
sent remotely

On Nov 29, 2013, at 2:58 PM, Scott Davis notifications@github.com wrote:

What do you mean by this? If there is a bad token sent to the PEL gp tasks?
Or is this related to https://redmine.dts.utah.gov/issues/28338?

—
Reply to this email directly or view it on
GitHubhttps://github.com/agrc/PEL/issues/43#issuecomment-29539115
.
