### ISSUE TITLE
change password widget

### ISSUE THREAD

**Issue by steveoh** [agrc/PEL#44]
nothing shows up when you click teh link. It just shows the modal background.

![screen shot 2013-12-03 at 6 03 27 pm](https://f.cloud.github.com/assets/325813/1669702/ec93c2e2-5c7f-11e3-8742-b7aae412aee0.png)

**Comment by steveoh** [comment]
its even weirder on my local box

![local dev](http://i.imgur.com/4UvwqQB.png)

**Comment by stdavis** [comment]
That gives the app "depth". :)

On Wed, Dec 4, 2013 at 10:57 AM, steve notifications@github.com wrote:

> its even weirder on my local box
> 
> [image: local dev]https://github-camo.global.ssl.fastly.net/98d95e42c879fd336237a612925ac40b3ded3be3/687474703a2f2f692e696d6775722e636f6d2f345576777151422e706e67
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/agrc/PEL/issues/44#issuecomment-29828464
> .

## 

_Scott Davis, GISP_
Utah AGRC http://gis.utah.gov/developer/
stdavis@utah.gov
@ScottAGRC https://twitter.com/ScottAGRC
