### ISSUE TITLE
Password Rules

### ISSUE THREAD

**Issue by brigsz** [agrc/PEL#53]
I would like to force a person to create a password with these rules.  I would also like to have this text presented to a user when they register on the site or change passwords etc.
1. [ ] Passwords must be at least 8 characters in length
2. [ ] Passwords must contain at least one character from three of the four following categories:
3. [ ] Uppercase characters (A to Z)
4. [ ] Lowercase characters (a to z)
5. [ ] Numbers (0 through 9)
6. [ ] Special characters: ~!@#$%^&*_-+=`|(){}[]:;'<>,.?/
7. [ ] Passwords will expire and must be changed after 90 days.
8. [ ] New passwords must be unique from previous passwords. Old passwords must not be re-used.
9. [ ] When changing a password, it is not acceptable to simply add a number to the end of a previously used password.

Can the following be confirmed in Staging?
"Currently Sarah Rigard and I are both able to approve requests but we do not both receive notice when someone is approved. Can we both be added to the cc list when permission is granted. I think Sarah is on the list but I am not. We both need to be notified when someone id approved."
![emailscreenshot](https://cloud.githubusercontent.com/assets/6306463/4510910/06b7c4b8-4b2f-11e4-84fc-009c3a405bbe.png)

**Comment by steveoh** [comment]
it will not be possible for us to do the last two.

**Comment by brigsz** [comment]
That sounds fine, I think as long as we are able to enforce an initial strong password that should work.

**Comment by stdavis** [comment]
You could do those checks on the client if you made them type in their old password on the same form as their new passwords.

**Comment by brigsz** [comment]
Ahhh, so that is probably how DTS does it.  I remember changing mine a week or so ago

**Comment by steveoh** [comment]
that would be a better UX in my opinion. 
![](http://gifs.joelglovier.com/chris-farley/farley-weekend-update.gif)

**Comment by stdavis** [comment]
It may require the changepassword service to accept an old password parameter.

**Comment by brigsz** [comment]
I believe what is in http://localhost:8000/src/app/tests/LoginRegisterCloudRequestPaneTests.html  looks good. consider this one done
