### ISSUE TITLE
Approval Email Notification

### ISSUE THREAD

**Issue by brigsz** [agrc/PEL#54]
Can the following be confirmed in Staging?
"Currently Sarah Rigard and I are both able to approve requests but we do not both receive notice when someone is approved. Can we both be added to the cc list when permission is granted. I think Sarah is on the list but I am not. We both need to be notified when someone id approved."
![emailscreenshot](https://cloud.githubusercontent.com/assets/6306463/4510964/c25f8b10-4b2f-11e4-9aa6-ec2306139f3b.png)

**Comment by stdavis** [comment]
I see both emails in staging. 
![image](https://cloud.githubusercontent.com/assets/1326248/4511155/830f9a16-4b31-11e4-926a-3949afdea357.png)

**Comment by brigsz** [comment]
Perfect, then this is complete, do you think?

**Comment by stdavis** [comment]
Yes.

On Fri, Oct 3, 2014 at 1:18 PM, Matt Peters notifications@github.com
wrote:

> Perfect, then this is complete, do you think?
> 
> On Fri, Oct 3, 2014 at 1:14 PM, Scott Davis notifications@github.com
> wrote:
> 
> > I see both emails in staging.
> > [image: image]
> > <
> > https://cloud.githubusercontent.com/assets/1326248/4511155/830f9a16-4b31-11e4-926a-3949afdea357.png>
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/agrc/PEL/issues/54#issuecomment-57840755.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agrc/PEL/issues/54#issuecomment-57841128.

## 

_Scott Davis, GISP_
Utah AGRC http://gis.utah.gov/developer/
stdavis@utah.gov
@ScottAGRC https://twitter.com/ScottAGRC
