### ISSUE TITLE
User Permission Management

### ISSUE THREAD

**Issue by brigsz** [agrc/PEL#55]
need the ui for users to be able to change their passwords.
Need a landing page for the user approve/reject emails. (more of an enhancement)
Urls in emails need to not use test hard coded information
need to make sure tokens on requests to secure services is solid.
have to enter user/password a lot. remember me checkbox work. (enhancement)

Just to add some clarification:
User Admin page updated to show list of users accepted(w/Roles) and pending users. A good option would be for admins to use admin page to accept users not just email. Enhancing page to have more admin functionality.

... for admins to use admin page to accept users not just email.

The admin page was designed to accept users. Email was an enhancement. Are you unable to accept users in the admin page?

Steve, you said.....
Looks like to me the only features from this issue that's not implemented is the list of existing users on the admin page. https://github.com/agrc/agrc.ijit/issues/48

**Comment by stdavis** [comment]
Yes, and I should have ijit#48 done by next week.

**Comment by brigsz** [comment]
Ahhhhhh!  You gave me a scare...I was just mindlessly working and all of a sudden you appeared!
