### ISSUE TITLE
10th of a Mile

### ISSUE THREAD

**Issue by brigsz** [agrc/PEL#58]
I believe I've found the problem. It is in the supporting Milepost Segment gp tool and not the PEL gp tool or the interface that we have been focusing on. I believe AGRC is using an older version of the pel_milepost_segment.py file.

I've put the updated file on Github and created a pull request. If Steve or someone else will accept and use the updated file I believe that will solve the issue.

FYI, the updated version creates a route event table and uses UDOT's LRS layer to create the polyline that is sent to the PEL gp tool. This method is very accurate and doesn't round to mileposts. It doesn't round at all.

**Comment by steveoh** [comment]
It also doesn't work properly. https://github.com/wkwells/pel-python/issues/8

**Comment by steveoh** [comment]
FYI this works on thousandths as well and probably further.
