### ISSUE TITLE
PEL Tool Instructions

### ISSUE THREAD

**Issue by brigsz** [agrc/PEL#61]
Please add a link under PEL user guide link in the upper left of the screen.  Call it "PEL How-to Guide"  Here is the link to the guide.  https://drive.google.com/a/utah.gov/file/d/0ByBPl4Mwaw9IYW9LLTA3eG1zYVE/view?usp=sharing

**Comment by steveoh** [comment]
What is the difference between a how to guide and a user guide?

**Comment by brigsz** [comment]
The how to guide is actual instructions on what button to push.  the user
guide is a narrative of the layers and their purpose etc.

**Comment by steveoh** [comment]
should it really contain a link to the test url of the application?

**Comment by steveoh** [comment]
Can we call the external link `About PEL` and this doc `User Guide`?

**Comment by brigsz** [comment]
Yes, that is the change that I know needs to be made.  Also yes, I am sure
your idea for naming is fine.

**Comment by steveoh** [comment]
This looks pretty good. Is it acceptable?

![image](https://cloud.githubusercontent.com/assets/325813/4567649/3aedd0da-4f33-11e4-8706-5eb051bf0682.png)

**Comment by brigsz** [comment]
I believe so.
