### ISSUE TITLE
Add login instructions to approval email

### ISSUE THREAD

**Issue by brigsz** [agrc/PEL#62]
Please change the confirmation email by removing the role from the email and including instructions to go back to uPEL with the link and login using the user name and password the person setup when they requested access. The reason for this, adding the PEL link and telling them what to do is because of the lag between when they register and when they are approved.  It can be a week or more.  I am trying to get the language for how this should be stated.

**Comment by steveoh** [comment]
I thought we decided this was a silly request and the user knowing their role was necessary.

**Comment by brigsz** [comment]
let me check RedMine, yes we definitely felt it was silly.....and why they can't approve users in a timely manner is not fair to the users

**Comment by brigsz** [comment]
okay, this is the line they want to use, but of course it will need to be updated with the "Real" URL.

"When you are approved you need to go to ThePELURL.utah.gov and log in with the user name password you provided."

**Comment by steveoh** [comment]
That seems fine but I would prefer not to remove the role.​
