### ISSUE TITLE
User Admin Page not dismissing

### ISSUE THREAD

**Issue by brigsz** [agrc/PEL#63]
When you are on the user admin page and choose to edit a users role, you hit the update button and it does not dismiss and update the role.  You are stuck just looking at the popup.  when you dismiss it manually with the X in the upper right, the role for the user is not changed.

**Comment by steveoh** [comment]
Can you reproduce this with a screen shot of your developer console and network tab?

**Comment by brigsz** [comment]
PUT https://test.mapserv.utah.gov/permissionproxy/api/admin/edit 404 (Not Found)

**Comment by brigsz** [comment]
![screen shot 2014-10-09 at 9 39 24 am](https://cloud.githubusercontent.com/assets/6306463/4579169/8d13bf68-4fca-11e4-9591-17d1783767a8.png)
