### ISSUE TITLE
User deletion and registering

### ISSUE THREAD

**Issue by brigsz** [agrc/PEL#64]
When testing Milestone 1, we noticed that once a user has been deleted, they may want to re-activate their account.  Instead they get a message saying it is a duplicate account.  Is this standard?  Or is there a way they can create the account with the same email?  If it is not possible to create an account a second time once the user has been deleted, can we make an exception for Corey Unger?  I deleted his account during test and know he cannot get back in.

**Comment by stdavis** [comment]
I believe that the delete service simply marks the account as inactive but doesn't actually delete the account (which I think is a good idea). So to re-enable the account we just need to manually set it to active in the database. I have made the changes in the database on the test server. He should now be able to log in using his old password. You should be able to reset his password if needed.

**Comment by brigsz** [comment]
The user was able to get in.

**Comment by brigsz** [comment]
When a user is deleted, the role get erased even though the login still exists in the table.
