### ISSUE TITLE
Retrieve Search Geometry from UDOT service

### ISSUE THREAD

**Issue by brigsz** [agrc/PEL#65]
I think we will need to speak with the UDOT folks for a minute about this one.  If I understood correctly they want to put in a PIN # and then use the geometry that is returned as the search criteria in the application.

Awhile back we talked about UDOT creating a simple EPM service to support a project PIN function for PEL. I just made the service today for another reason so I thought I would pass along the rest service link in case it is of use to you:

http://maps.udot.utah.gov/arcgis/rest/services/EPM_Projects/FeatureServer

This service has the three geometry types for EPM (point, line, and polygon) however it is not broken out by all the project categories.

**Comment by brigsz** [comment]
In our EPM data the PIN field is a double type. And, all PINs are 4 or 5 digit integers

**Comment by steveoh** [comment]
So query all 3 feature classes where PIN = some number and one of the 3 feature classes will have a value? Are pin numbers unique? What if the PIN is in the points, polygon, an lines feature class?

**Comment by brigsz** [comment]
I have that question into the client now.  I will respond here when they check the data

**Comment by brigsz** [comment]
I just wanted to capture these statements from the client.

You can also have multiple lines within a dataset reference the same PIN.
You can have a line and poly have the same PIN
PINs are unique at the project level. You can have multiple geometries and multipart.

**Comment by steveoh** [comment]
Test data:

`10814` - multiple multipoints no polylines
`1560` - multiple polylines no mulitpoints
`4184`, `13202` - polylines and multipoints

**Comment by steveoh** [comment]
do you want me to publish the partially complete feature to start the testing?

**Comment by brigsz** [comment]
I believe so.

Thanks

On Nov 19, 2014, at 6:59 PM, steveoh notifications@github.com wrote:

do you want me to publish the partially complete feature to start the
testing?
