### ISSUE TITLE
Shapefile upload

### ISSUE THREAD

**Issue by brigsz** [agrc/PEL#66]
PEL Shapefile Upload Needs

Geometry Types:
Polygon
Polyline

Output
Run each shapefile as one project, producing one report
Allow for multipart features to be analyzed as one project. I.e. A project that might span two unique road segments, or a project that might have a gap in it.

**Comment by steveoh** [comment]
I am going to read all rows of the shapefile and union the geometries into one multipart feature to be used as the input geometry. If that is not what is expected please let me know as soon as you can.

**Comment by brigsz** [comment]
That is the correct thing to do, from what I understand

**Comment by steveoh** [comment]
this already works this way.
