### ISSUE TITLE
Polygon Buffer

### ISSUE THREAD

**Issue by brigsz** [agrc/PEL#67]
Buffer Entry:
Ask that the user enter the total width of the project area.
Then divide the number entered in half for the buffer analysis for the tool. Most nonGIS users will think of the buffer as the full width, not the radius. 
No buffer should be the default for polygon shapefile analysis. The polygon may be the impact area itself and may not require any additional buffering.

**Comment by steveoh** [comment]
this was fixed in [0.6.4](https://github.com/agrc/PEL/commit/af303769cd14a84e36496cb1501c380781d79700)
