### ISSUE TITLE
Polygon Buffers

### ISSUE THREAD

**Issue by brigsz** [agrc/PEL#76]
In Firefox I am not able to create a categorical exclusion or a main report choosing a zero buffer and the "within a polygon" choice.  It comes back and says, "I'm sorry but the job failed"  However it does work in Chrome. If I give it a 5 foot Project Width, it completes successfully and produces a report in FF.

below is the URL for the categorical exclusion.

https://test.mapserv.utah.gov/arcgis/rest/services/PEL/Toolbox/GPServer/WebReport/submitJob?f=json&bufferDistance=0&polygons=%7B%22geometryType%22%3A%22esriGeometryPolygon%22%2C%22features%22%3A%5B%7B%22geometry%22%3A%7B%22rings%22%3A%5B%5B%5B448595.58184031205%2C4374525.823997495%5D%2C%5B449149.75029537885%2C4374372.9499409245%5D%2C%5B449512.8261797329%2C4374200.966627283%5D%2C%5B450353.6334908687%2C4373474.814858574%5D%2C%5B448557.3633261695%2C4373665.907429287%5D%2C%5B448595.58184031205%2C4374525.823997495%5D%5D%5D%2C%22spatialReference%22%3A%7B%22wkid%22%3A26912%7D%7D%7D%5D%2C%22sr%22%3A%7B%22wkid%22%3A26912%7D%7D&planner=test%40test.com&projectName=TestFFbuf0&reportType=0&token=dQFwe9CM-DDkogccp2jcNdWc0drLFnT3xg8axbrRehI.

**Comment by steveoh** [comment]
It does and doesn't work in chrome?

**Comment by steveoh** [comment]
What is the expected outcome?

**Comment by brigsz** [comment]
I am having a rough time trying to copy and paste the parameters from the JS console in FF.  It is parsed out nicely I just can't capture it

This process does work in Chrome.

**Comment by brigsz** [comment]
a categorical exclusion or main report is the expected outcome for each option, if the choice "within a polygon is chosen, a buffer should not be required and in fact it doesn't make sense if you buffer it.  If a polygon is uploaded then a buffer may be entered, though not required.
