### ISSUE TITLE
Segment Length and Polygon Area Threshold

### ISSUE THREAD

**Issue by stdavis** [agrc/PEL#8]
Need to prevent the user from drawing too long of a line or too big of a polygon. 

It would be best to give feedback while the user is drawing.

**Comment by steveoh** [comment]
this seemed to be an arbitrary number from whatever scale level the map was at. It did not take into account a buffer that could be applied. It was not checked for in the GP tool. 

I think we should do what the original PEL did with the scale level for this milestone and enhance later if necessary.

**Comment by stdavis** [comment]
Gross.

On Thu, Oct 10, 2013 at 4:11 PM, steve notifications@github.com wrote:

> this seemed to be an arbitrary number from whatever scale level the map
> was at. It did not take into account a buffer that could be applied. It was
> not checked for in the GP tool.
> 
> I think we should do what the original PEL did with the scale level for
> this milestone and enhance later if necessary.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/agrc/PEL/issues/8#issuecomment-26096107
> .

## 

_Scott Davis, GISP_
Utah AGRC http://gis.utah.gov/developer/
stdavis@utah.gov
@ScottAGRC https://twitter.com/ScottAGRC
