### ISSUE TITLE
Project Width Value Verification

### ISSUE THREAD

**Issue by brigsz** [agrc/PEL#80]
Is the project width/diameter entered, or is the project radius or the width from the centerline entered? We used to enter the project radius, but I think it was revised to use the full width since that is more intuitive for users, correct?

This is the section I'm referring to:

![image](https://cloud.githubusercontent.com/assets/6306463/7352146/21cfd08a-ecc7-11e4-9d0d-323b8b72af59.png)

**Comment by steveoh** [comment]
https://github.com/agrc/PEL/blob/6af184a382d635feaddda100c91231a4bb9a6330/src/app/_ReportGeometryWizardPane.js#L72-L79

**Comment by brigsz** [comment]
It is the radius or the width from centerline
